# Generated by Django 4.0.6 on 2022-07-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='description',
            field=models.TextField(help_text='Descripción', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='email',
            field=models.EmailField(help_text='Email', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='identification_type',
            field=models.CharField(choices=[('cedula', 'Cédula'), ('tarjeta de identidad', 'Tarjeta de identidad'), ('cedula de Extranjería', 'Cedula de Extranjería')], default='cedula', help_text='Tipo de identificación', max_length=25, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='last_name',
            field=models.CharField(help_text='Apellido', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='name',
            field=models.CharField(help_text='Nombre', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='title',
            field=models.CharField(help_text='Título', max_length=100, verbose_name='Título'),
        ),
    ]
